version: 0.1
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "zipping deployement package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
      - zip -g deployment_package.zip .env
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://github-s3-source-code-cicd/
      - echo "Updating lambda function via S3..."
      - aws lambda update-function-code --function-name s3-read-lambda-ontrigger-sns --s3-bucket github-s3-source-code-cicd --s3-key deployment_package.zip
      - |
        aws lambda add-permission \
          --function-name s3-read-lambda-ontrigger-sns \
          --statement-id S3EventTrigger \
          --action "lambda:InvokeFunction" \
          --principal s3.amazonaws.com \
          --source-arn arn:aws:s3:::doordash-landing-growskills-zn \
          --source-account 975049912631 \
          --source-region us-east-2 \
      - |
        aws s3api put-bucket-notification-configuration \
          --bucket doordash-landing-growskills-zn \
          --notification-configuration '{
            "LambdaFunctionConfigurations": [
              {
                "LambdaFunctionArn": "arn:aws:lambda:us-east-2:975049912631:function:s3-read-lambda-ontrigger-sns",
                "Events": ["s3:ObjectCreated:*"]
              }
            ]
          }' \
      - echo "Deployment complete!!"
